// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD283r_vehhGJfYEgFFSRl79HVofxASrs',
    appId: '1:273596692474:web:c77d6f5c63ee002d9b5643',
    messagingSenderId: '273596692474',
    projectId: 'dolcecatapp-dev',
    authDomain: 'dolcecatapp-dev.firebaseapp.com',
    storageBucket: 'dolcecatapp-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKlLf1_UvSuumpq1Df2_IQGRBBAAg_D9E',
    appId: '1:273596692474:android:73cb2232867f4f6b9b5643',
    messagingSenderId: '273596692474',
    projectId: 'dolcecatapp-dev',
    storageBucket: 'dolcecatapp-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS1rDFpXK9zpA1vrNKI4YRbh8FHI3h5Hw',
    appId: '1:273596692474:ios:04ef37617b41e8609b5643',
    messagingSenderId: '273596692474',
    projectId: 'dolcecatapp-dev',
    storageBucket: 'dolcecatapp-dev.firebasestorage.app',
    iosBundleId: 'com.example.registrosReposteria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS1rDFpXK9zpA1vrNKI4YRbh8FHI3h5Hw',
    appId: '1:273596692474:ios:04ef37617b41e8609b5643',
    messagingSenderId: '273596692474',
    projectId: 'dolcecatapp-dev',
    storageBucket: 'dolcecatapp-dev.firebasestorage.app',
    iosBundleId: 'com.example.registrosReposteria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD283r_vehhGJfYEgFFSRl79HVofxASrs',
    appId: '1:273596692474:web:b3d0775f77d0c63c9b5643',
    messagingSenderId: '273596692474',
    projectId: 'dolcecatapp-dev',
    authDomain: 'dolcecatapp-dev.firebaseapp.com',
    storageBucket: 'dolcecatapp-dev.firebasestorage.app',
  );
}
