// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAL-Y29VMmP7yrkN31mH_G6hIgX_qmZPQ',
    appId: '1:750898760438:web:135afac17c2d6568e63ad7',
    messagingSenderId: '750898760438',
    projectId: 'dolcecatapp',
    authDomain: 'dolcecatapp.firebaseapp.com',
    storageBucket: 'dolcecatapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS7XNfCKKDDR1sSE_Xdql3vkM5YHCIsyI',
    appId: '1:750898760438:android:a3da73b7cb32a474e63ad7',
    messagingSenderId: '750898760438',
    projectId: 'dolcecatapp',
    storageBucket: 'dolcecatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBy2Dw9i6Py4lROPowfYmoSHUPAbwgAMg',
    appId: '1:750898760438:ios:98edc91bac8dbac2e63ad7',
    messagingSenderId: '750898760438',
    projectId: 'dolcecatapp',
    storageBucket: 'dolcecatapp.firebasestorage.app',
    iosBundleId: 'com.example.registrosReposteria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBy2Dw9i6Py4lROPowfYmoSHUPAbwgAMg',
    appId: '1:750898760438:ios:98edc91bac8dbac2e63ad7',
    messagingSenderId: '750898760438',
    projectId: 'dolcecatapp',
    storageBucket: 'dolcecatapp.firebasestorage.app',
    iosBundleId: 'com.example.registrosReposteria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAL-Y29VMmP7yrkN31mH_G6hIgX_qmZPQ',
    appId: '1:750898760438:web:5d2e2fbc2d7b99b8e63ad7',
    messagingSenderId: '750898760438',
    projectId: 'dolcecatapp',
    authDomain: 'dolcecatapp.firebaseapp.com',
    storageBucket: 'dolcecatapp.firebasestorage.app',
  );

}